package frames;

import bdmysql.SqlArticulo;
import clases.Producto;
import clases.Usuario;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;


/**
 *
 * @author usuario
 */
public class Catalogo extends javax.swing.JFrame {
    //Declaración de constantes
    private static final String FUENTE1 = "Trebuchet MS";
    private static final String CARRITO = "Carrito";
    private static final String CATEGORIA = "Categorías";
    //Declaración de objetos
    List <Producto> art = new ArrayList<>(); 
    SqlArticulo consultaP = new SqlArticulo();
    org.edisoncor.gui.panel.PanelImage [] paneles = new  org.edisoncor.gui.panel.PanelImage [6];
    javax.swing.JLabel [] labels = new javax.swing.JLabel[42];
    Producto [] producto = new Producto [6];
    Usuario usr;
    int posInicial = 0; 
    String tipo, genero;
    
    public Catalogo(){
        initComponents();
        llenarVector();
        consultaP.obtenerProducto(art);
        setLocationRelativeTo(null);
        setResizable(false);
    }
    
    public void setUsuario(Usuario usr){
        this.usr = usr;
    }
    
    public void seleccionP (List <Producto> art, String genero, String tipo){
        int posFinal = Math.min(posInicial + 6, art.size());
        int j = 0;
        limpiarCatalogo();
        for (int i = posInicial; j < 6 && i < art.size(); i++) {
            if (art.get(i).getGenero().equals(genero) && art.get(i).getTipo().equals(tipo)){
                String image = art.get(i).getImage();
                try{
                    paneles[j].setIcon(new javax.swing.ImageIcon (getClass().getResource(image)));
                    paneles[j].repaint();
                }catch(Exception e){
                     JOptionPane.showMessageDialog(null, "Error al cargar imagen: ", "Error de carga", JOptionPane.ERROR_MESSAGE);
                }
                labels[j].setText(strHTML(art.get(i).getDescripcion()));
                producto[j] = art.get(i);
                j++;
            }
        }
        if(posFinal >= art.size() || j < 6){
            btnSiguiente.setEnabled(false);
        }
    }
    
    public void busquedaP (List <Producto> art, String termino){
        int posFinal = Math.min(posInicial + 6, art.size());
        int j = 0;
        limpiarCatalogo();
        for (int i = posInicial; j < 6 && i < art.size(); i++) {
            if (art.get(i).getDescripcion().toLowerCase().contains(termino.toLowerCase())){
                String image = art.get(i).getImage();
                paneles[j].setIcon(new javax.swing.ImageIcon (getClass().getResource(image)));
                paneles[j].repaint();
                labels[j].setText(art.get(i).getDescripcion());
                producto[j] = art.get(i);
                j++;
            }
        }
        if(posFinal >= art.size() || j < 6){
            btnSiguiente.setEnabled(false);
        }
    }
    
    public void llenarCatalogo (List <Producto> art){
        int i = 0;
        for (Producto articulo : art) {
            if (articulo != null){
                paneles[i].setIcon(new javax.swing.ImageIcon (getClass().getResource(articulo.getImage())));
                paneles[i].repaint();
                labels[i].setText(articulo.getDescripcion());
            }
            i++;
        }
    }
    public void limpiarCatalogo(){
        for (int i = 0; i < 6; i++){
            paneles[i].setIcon(new javax.swing.ImageIcon (getClass().getResource("/images/delete.jpg")));
            paneles[i].repaint();
            labels[i].setText("");
        }
    }
    
    public void abrirCarrito(int ind){
        if (producto[ind] != null){
            AgregarCarrito agregar = new AgregarCarrito();
            agregar.iniciarComponentes(producto[ind]);
            agregar.setUsuario(usr);
            agregar.setVisible(true);
            agregar.setFrame(this);
            agregar.toFront();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel pnlMenu = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        panelCategoria = new javax.swing.JPanel();
        panelImage4 = new org.edisoncor.gui.panel.PanelImage();
        javax.swing.JLabel lblRegi1 = new javax.swing.JLabel();
        javax.swing.JPanel panelCompras = new javax.swing.JPanel();
        javax.swing.JLabel lblRegi5 = new javax.swing.JLabel();
        panelImage5 = new org.edisoncor.gui.panel.PanelImage();
        javax.swing.JPanel pnlCarrito = new javax.swing.JPanel();
        javax.swing.JLabel lblRegi4 = new javax.swing.JLabel();
        panelImage18 = new org.edisoncor.gui.panel.PanelImage();
        javax.swing.JPanel pnlCerrarSesion = new javax.swing.JPanel();
        javax.swing.JLabel lblCerrarS1 = new javax.swing.JLabel();
        panelImage19 = new org.edisoncor.gui.panel.PanelImage();
        javax.swing.JLabel lblBienvenido = new javax.swing.JLabel();
        org.edisoncor.gui.panel.PanelImage panelImage17 = new org.edisoncor.gui.panel.PanelImage();
        javax.swing.JPanel pnlSuperior = new javax.swing.JPanel();
        pnlLupa = new org.edisoncor.gui.panel.PanelImage();
        txtBuscar = new javax.swing.JTextField();
        jtpMenu = new javax.swing.JTabbedPane();
        javax.swing.JPanel pnlCateg = new javax.swing.JPanel();
        org.edisoncor.gui.panel.PanelImage panelImage7 = new org.edisoncor.gui.panel.PanelImage();
        org.edisoncor.gui.panel.PanelImage pnlHombre = new org.edisoncor.gui.panel.PanelImage();
        org.edisoncor.gui.panel.PanelImage pnlMujer = new org.edisoncor.gui.panel.PanelImage();
        org.edisoncor.gui.panel.PanelImage pnlCaballero = new org.edisoncor.gui.panel.PanelImage();
        javax.swing.JPanel pnlTipoP = new javax.swing.JPanel();
        javax.swing.JPanel pnlZapatillasEv = new javax.swing.JPanel();
        javax.swing.JPanel pnPantalonesEv = new javax.swing.JPanel();
        javax.swing.JPanel pnPolosEv = new javax.swing.JPanel();
        javax.swing.JPanel pnZapatosEv = new javax.swing.JPanel();
        javax.swing.JPanel pnCamisasEv = new javax.swing.JPanel();
        javax.swing.JPanel pnPolerasEv = new javax.swing.JPanel();
        org.edisoncor.gui.panel.PanelImage panelImage11 = new org.edisoncor.gui.panel.PanelImage();
        org.edisoncor.gui.panel.PanelImage panelImage12 = new org.edisoncor.gui.panel.PanelImage();
        org.edisoncor.gui.panel.PanelImage panelImage13 = new org.edisoncor.gui.panel.PanelImage();
        org.edisoncor.gui.panel.PanelImage panelImage14 = new org.edisoncor.gui.panel.PanelImage();
        org.edisoncor.gui.panel.PanelImage panelImage15 = new org.edisoncor.gui.panel.PanelImage();
        org.edisoncor.gui.panel.PanelImage panelImage16 = new org.edisoncor.gui.panel.PanelImage();
        lblCamisas = new javax.swing.JLabel();
        lblPolos = new javax.swing.JLabel();
        lblZapatillas = new javax.swing.JLabel();
        lblPoleras = new javax.swing.JLabel();
        lblZapatos = new javax.swing.JLabel();
        lblPantalones = new javax.swing.JLabel();
        javax.swing.JPanel pnlProductos1 = new javax.swing.JPanel();
        imProducto1 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto1 = new javax.swing.JLabel();
        imProducto2 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto2 = new javax.swing.JLabel();
        imProducto3 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto3 = new javax.swing.JLabel();
        imProducto4 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto4 = new javax.swing.JLabel();
        imProducto5 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto5 = new javax.swing.JLabel();
        imProducto6 = new org.edisoncor.gui.panel.PanelImage();
        lblProducto6 = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setBackground(new java.awt.Color(86, 105, 204));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setFont(new java.awt.Font(FUENTE1, 1, 16));
        lblNombre.setForeground(new java.awt.Color(235, 235, 235));
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlMenu.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 220, 40));

        panelCategoria.setBackground(new java.awt.Color(86, 105, 204));
        panelCategoria.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelCategoria.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelCategoriaMouseMoved(evt);
            }
        });
        panelCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelCategoriaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelCategoriaMouseExited(evt);
            }
        });
        panelCategoria.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelImage4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/categoria.png"))); // NOI18N
        panelCategoria.add(panelImage4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 13, 65, 65));

        lblRegi1.setFont(new java.awt.Font(FUENTE1, 1, 18));
        lblRegi1.setForeground(new java.awt.Color(255, 255, 255));
        lblRegi1.setText(CATEGORIA);
        panelCategoria.add(lblRegi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 140, 30));

        pnlMenu.add(panelCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 270, 80));

        panelCompras.setBackground(new java.awt.Color(86, 105, 204));
        panelCompras.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelCompras.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                panelComprasMouseMoved(evt);
            }
        });
        panelCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelComprasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelComprasMouseExited(evt);
            }
        });
        panelCompras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRegi5.setFont(new java.awt.Font(FUENTE1, 1, 18));
        lblRegi5.setForeground(new java.awt.Color(255, 255, 255));
        lblRegi5.setText("Mis compras");
        panelCompras.add(lblRegi5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 140, 30));

        panelImage5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/compra1.png"))); // NOI18N
        panelCompras.add(panelImage5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 13, 65, 65));

        pnlMenu.add(panelCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 270, 80));

        pnlCarrito.setBackground(new java.awt.Color(86, 105, 204));
        pnlCarrito.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnlCarrito.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlCarritoMouseMoved(evt);
            }
        });
        pnlCarrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCarritoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlCarritoMouseExited(evt);
            }
        });
        pnlCarrito.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRegi4.setFont(new java.awt.Font(FUENTE1, 1, 18));
        lblRegi4.setForeground(new java.awt.Color(255, 255, 255));
        lblRegi4.setText(CARRITO);
        pnlCarrito.add(lblRegi4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 140, 30));

        panelImage18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carrito2.png"))); // NOI18N
        pnlCarrito.add(panelImage18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 65, 65));

        pnlMenu.add(pnlCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 270, 80));

        pnlCerrarSesion.setBackground(new java.awt.Color(86, 105, 204));
        pnlCerrarSesion.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnlCerrarSesion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlCerrarSesionMouseMoved(evt);
            }
        });
        pnlCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCerrarSesionMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlCerrarSesionMouseExited(evt);
            }
        });
        pnlCerrarSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCerrarS1.setFont(new java.awt.Font(FUENTE1, 1, 18));
        lblCerrarS1.setForeground(new java.awt.Color(255, 255, 255));
        lblCerrarS1.setText("Cerrar Sesión");
        pnlCerrarSesion.add(lblCerrarS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 25, 140, 30));

        panelImage19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/salir0.png"))); // NOI18N
        pnlCerrarSesion.add(panelImage19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 65, 65));

        pnlMenu.add(pnlCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 270, 80));

        lblBienvenido.setFont(new java.awt.Font(FUENTE1, 1, 18));
        lblBienvenido.setForeground(new java.awt.Color(255, 255, 255));
        lblBienvenido.setText("¡Bienvenido!");
        pnlMenu.add(lblBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 110, 40));

        panelImage17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconFisiStyle.png"))); // NOI18N
        pnlMenu.add(panelImage17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 210, 170));

        getContentPane().add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 720));

        pnlSuperior.setBackground(new java.awt.Color(85, 105, 204));
        pnlSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLupa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lupa.png"))); // NOI18N
        pnlSuperior.add(pnlLupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 50, 50));

        txtBuscar.setBackground(new java.awt.Color(228, 228, 228));
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });
        pnlSuperior.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 330, 30));

        getContentPane().add(pnlSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 980, 130));

        pnlCateg.setBackground(new java.awt.Color(255, 255, 255));
        pnlCateg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelImage7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Boton Dama Categoria.png"))); // NOI18N
        panelImage7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelImage7MouseClicked(evt);
            }
        });
        pnlCateg.add(panelImage7, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 463, 220, 76));

        pnlHombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Hombre categoria.png"))); // NOI18N
        pnlCateg.add(pnlHombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 108, 220, 280));

        pnlMujer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Mujer categ.png"))); // NOI18N
        pnlCateg.add(pnlMujer, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 108, 220, 280));

        pnlCaballero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Boton Caballero Categoria.png"))); // NOI18N
        pnlCaballero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlCaballeroMouseClicked(evt);
            }
        });
        pnlCateg.add(pnlCaballero, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 463, 220, 76));

        jtpMenu.addTab("Categorias", pnlCateg);

        pnlTipoP.setBackground(new java.awt.Color(255, 255, 255));
        pnlTipoP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlZapatillasEv.setBackground(new java.awt.Color(51, 51, 51));
        pnlZapatillasEv.setOpaque(false);
        pnlZapatillasEv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlZapatillasEvMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlZapatillasEvLayout = new javax.swing.GroupLayout(pnlZapatillasEv);
        pnlZapatillasEv.setLayout(pnlZapatillasEvLayout);
        pnlZapatillasEvLayout.setHorizontalGroup(
            pnlZapatillasEvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        pnlZapatillasEvLayout.setVerticalGroup(
            pnlZapatillasEvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        pnlTipoP.add(pnlZapatillasEv, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 210, 230));

        pnPantalonesEv.setOpaque(false);
        pnPantalonesEv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnPantalonesEvMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnPantalonesEvLayout = new javax.swing.GroupLayout(pnPantalonesEv);
        pnPantalonesEv.setLayout(pnPantalonesEvLayout);
        pnPantalonesEvLayout.setHorizontalGroup(
            pnPantalonesEvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        pnPantalonesEvLayout.setVerticalGroup(
            pnPantalonesEvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        pnlTipoP.add(pnPantalonesEv, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 210, 230));

        pnPolosEv.setOpaque(false);
        pnPolosEv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnPolosEvMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnPolosEvLayout = new javax.swing.GroupLayout(pnPolosEv);
        pnPolosEv.setLayout(pnPolosEvLayout);
        pnPolosEvLayout.setHorizontalGroup(
            pnPolosEvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        pnPolosEvLayout.setVerticalGroup(
            pnPolosEvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        pnlTipoP.add(pnPolosEv, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 210, 230));

        pnZapatosEv.setOpaque(false);
        pnZapatosEv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnZapatosEvMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnZapatosEvLayout = new javax.swing.GroupLayout(pnZapatosEv);
        pnZapatosEv.setLayout(pnZapatosEvLayout);
        pnZapatosEvLayout.setHorizontalGroup(
            pnZapatosEvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        pnZapatosEvLayout.setVerticalGroup(
            pnZapatosEvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        pnlTipoP.add(pnZapatosEv, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 210, 230));

        pnCamisasEv.setOpaque(false);
        pnCamisasEv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnCamisasEvMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnCamisasEvLayout = new javax.swing.GroupLayout(pnCamisasEv);
        pnCamisasEv.setLayout(pnCamisasEvLayout);
        pnCamisasEvLayout.setHorizontalGroup(
            pnCamisasEvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        pnCamisasEvLayout.setVerticalGroup(
            pnCamisasEvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        pnlTipoP.add(pnCamisasEv, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 210, 230));

        pnPolerasEv.setOpaque(false);
        pnPolerasEv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnPolerasEvMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnPolerasEvLayout = new javax.swing.GroupLayout(pnPolerasEv);
        pnPolerasEv.setLayout(pnPolerasEvLayout);
        pnPolerasEvLayout.setHorizontalGroup(
            pnPolerasEvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        pnPolerasEvLayout.setVerticalGroup(
            pnPolerasEvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        pnlTipoP.add(pnPolerasEv, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 210, 230));

        panelImage11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tipo Zatapatilla.png"))); // NOI18N
        pnlTipoP.add(panelImage11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 210, 170));

        panelImage12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tipo Camisas.png"))); // NOI18N
        pnlTipoP.add(panelImage12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 210, 170));

        panelImage13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tipo Polos.png"))); // NOI18N
        pnlTipoP.add(panelImage13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 210, 170));

        panelImage14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tipo Poleras.png"))); // NOI18N
        pnlTipoP.add(panelImage14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 210, 170));

        panelImage15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tipo Zapatos.png"))); // NOI18N
        pnlTipoP.add(panelImage15, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 210, 170));

        panelImage16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Tipo Pantalones.png"))); // NOI18N
        pnlTipoP.add(panelImage16, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 210, 170));

        lblCamisas.setFont(new java.awt.Font(FUENTE1, 1, 18));
        lblCamisas.setForeground(new java.awt.Color(0, 0, 0));
        lblCamisas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCamisas.setText("Camisas");
        pnlTipoP.add(lblCamisas, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 210, 30));

        lblPolos.setFont(new java.awt.Font(FUENTE1, 1, 18));
        lblPolos.setForeground(new java.awt.Color(0, 0, 0));
        lblPolos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPolos.setText("Polos");
        pnlTipoP.add(lblPolos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, 210, 30));

        lblZapatillas.setFont(new java.awt.Font(FUENTE1, 1, 18));
        lblZapatillas.setForeground(new java.awt.Color(0, 0, 0));
        lblZapatillas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblZapatillas.setText("Zapatillas");
        pnlTipoP.add(lblZapatillas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 210, 30));

        lblPoleras.setFont(new java.awt.Font(FUENTE1, 1, 18));
        lblPoleras.setForeground(new java.awt.Color(0, 0, 0));
        lblPoleras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPoleras.setText("Poleras");
        pnlTipoP.add(lblPoleras, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 210, 30));

        lblZapatos.setFont(new java.awt.Font(FUENTE1, 1, 18));
        lblZapatos.setForeground(new java.awt.Color(0, 0, 0));
        lblZapatos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblZapatos.setText("Zapatos");
        pnlTipoP.add(lblZapatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, 210, 30));

        lblPantalones.setFont(new java.awt.Font(FUENTE1, 1, 18));
        lblPantalones.setForeground(new java.awt.Color(0, 0, 0));
        lblPantalones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPantalones.setText("Pantalones");
        pnlTipoP.add(lblPantalones, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, 210, 30));

        jtpMenu.addTab("Tipos", pnlTipoP);

        pnlProductos1.setBackground(new java.awt.Color(255, 255, 255));
        pnlProductos1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imProducto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imProducto1MouseClicked(evt);
            }
        });
        imProducto1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlProductos1.add(imProducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 210, 170));

        lblProducto1.setFont(new java.awt.Font(FUENTE1, 1, 18));
        lblProducto1.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProducto1.setInheritsPopupMenu(false);
        pnlProductos1.add(lblProducto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 210, 30));

        imProducto2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imProducto2MouseClicked(evt);
            }
        });
        pnlProductos1.add(imProducto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 210, 170));

        lblProducto2.setFont(new java.awt.Font(FUENTE1, 1, 18));
        lblProducto2.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProducto2.setInheritsPopupMenu(false);
        pnlProductos1.add(lblProducto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 210, 30));

        imProducto3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imProducto3MouseClicked(evt);
            }
        });
        pnlProductos1.add(imProducto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 210, 170));

        lblProducto3.setFont(new java.awt.Font(FUENTE1, 1, 18));
        lblProducto3.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProducto3.setInheritsPopupMenu(false);
        pnlProductos1.add(lblProducto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 210, 30));

        imProducto4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imProducto4MouseClicked(evt);
            }
        });
        pnlProductos1.add(imProducto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 210, 170));

        lblProducto4.setFont(new java.awt.Font(FUENTE1, 1, 18));
        lblProducto4.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProducto4.setInheritsPopupMenu(false);
        pnlProductos1.add(lblProducto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 210, 30));

        imProducto5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imProducto5MouseClicked(evt);
            }
        });
        pnlProductos1.add(imProducto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 210, 170));

        lblProducto5.setFont(new java.awt.Font(FUENTE1, 1, 18));
        lblProducto5.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProducto5.setInheritsPopupMenu(false);
        pnlProductos1.add(lblProducto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 210, 30));

        imProducto6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imProducto6MouseClicked(evt);
            }
        });
        pnlProductos1.add(imProducto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 210, 170));

        lblProducto6.setFont(new java.awt.Font(FUENTE1, 1, 18));
        lblProducto6.setForeground(new java.awt.Color(0, 0, 0));
        lblProducto6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProducto6.setInheritsPopupMenu(false);
        pnlProductos1.add(lblProducto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, 210, 30));

        btnSiguiente.setBackground(new java.awt.Color(255, 153, 0));
        btnSiguiente.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        btnSiguiente.setText("SIGUIENTE");
        btnSiguiente.setBorder(null);
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        pnlProductos1.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 470, 70, 60));

        jtpMenu.addTab("Productos 1", pnlProductos1);

        getContentPane().add(jtpMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 980, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void llenarVector(){
        paneles [0] = imProducto1;
        paneles [1] = imProducto2;
        paneles [2] = imProducto3;
        paneles [3] = imProducto4;
        paneles [4] = imProducto5;
        paneles [5] = imProducto6;
        labels [0] = lblProducto1;
        labels [1] = lblProducto2;
        labels [2] = lblProducto3;
        labels [3] = lblProducto4;
        labels [4] = lblProducto5;
        labels [5] = lblProducto6;
    }
    
    private void filtrar(){
        seleccionP(art,genero,tipo);
        jtpMenu.setSelectedIndex(2);
    }
    
    public String strHTML (String text){
        return "<html><p>" + text + "</p></html>";
    }
    
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked
    
    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        jtpMenu.setSelectedIndex(2); 
        String termino;
        termino = txtBuscar.getText();
        busquedaP(art,termino);
        if (txtBuscar.getText().equals(""))
            jtpMenu.setSelectedIndex(1); 
    }//GEN-LAST:event_txtBuscarKeyTyped
    
    private void panelImage7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelImage7MouseClicked
        jtpMenu.setSelectedIndex(1);
        genero = "Dama";
        evt.consume();
    }//GEN-LAST:event_panelImage7MouseClicked

    private void pnlCaballeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCaballeroMouseClicked
        jtpMenu.setSelectedIndex(1);
        genero = "Caballero";
        evt.consume();
    }//GEN-LAST:event_pnlCaballeroMouseClicked

    private void pnlZapatillasEvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlZapatillasEvMouseClicked
        tipo = lblZapatillas.getText();
        filtrar();
        evt.consume();
    }//GEN-LAST:event_pnlZapatillasEvMouseClicked

    private void pnPantalonesEvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnPantalonesEvMouseClicked
        tipo = lblPantalones.getText();
        filtrar();
        evt.consume();
    }//GEN-LAST:event_pnPantalonesEvMouseClicked

    private void pnPolosEvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnPolosEvMouseClicked
        tipo = lblPolos.getText();
        filtrar();
        evt.consume();
    }//GEN-LAST:event_pnPolosEvMouseClicked

    private void pnZapatosEvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnZapatosEvMouseClicked
        tipo = lblZapatos.getText();
        filtrar();
        evt.consume();
    }//GEN-LAST:event_pnZapatosEvMouseClicked

    private void pnCamisasEvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnCamisasEvMouseClicked
        tipo = lblCamisas.getText();
        filtrar();
        evt.consume();
    }//GEN-LAST:event_pnCamisasEvMouseClicked

    private void pnPolerasEvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnPolerasEvMouseClicked
        tipo = lblPoleras.getText();
        filtrar();
        evt.consume();
    }//GEN-LAST:event_pnPolerasEvMouseClicked

    private void pnlCerrarSesionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCerrarSesionMouseMoved
        //MouseMoved
        evt.consume();
    }//GEN-LAST:event_pnlCerrarSesionMouseMoved

    private void pnlCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCerrarSesionMouseClicked
       int resp = JOptionPane.showConfirmDialog(null, "¿Está seguro desea salir?", "Cerrar sesión", JOptionPane.YES_NO_OPTION);
        if (resp == 0){
            Login log = new Login();
            this.dispose();
            log.setVisible(true);
        }
        evt.consume();
    }//GEN-LAST:event_pnlCerrarSesionMouseClicked

    private void pnlCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCerrarSesionMouseExited
        //MouseExited
        evt.consume();
    }//GEN-LAST:event_pnlCerrarSesionMouseExited

    private void panelCategoriaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCategoriaMouseMoved
        //MouseMoved
        evt.consume();
    }//GEN-LAST:event_panelCategoriaMouseMoved

    private void panelCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCategoriaMouseClicked
        //MouseClicked
        jtpMenu.setSelectedIndex(0);
        evt.consume();
    }//GEN-LAST:event_panelCategoriaMouseClicked

    private void panelCategoriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCategoriaMouseExited
        //MouseExited
        evt.consume();
    }//GEN-LAST:event_panelCategoriaMouseExited

    private void pnlCarritoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCarritoMouseMoved
        //MouseMoved
        evt.consume();
    }//GEN-LAST:event_pnlCarritoMouseMoved

    private void pnlCarritoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCarritoMouseClicked
        //MouseClicked
        evt.consume();
    }//GEN-LAST:event_pnlCarritoMouseClicked

    private void pnlCarritoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCarritoMouseExited
        //MouseExited
        evt.consume();
    }//GEN-LAST:event_pnlCarritoMouseExited

    private void panelComprasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelComprasMouseMoved
        //MouseMoved
        evt.consume();
    }//GEN-LAST:event_panelComprasMouseMoved

    private void panelComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelComprasMouseClicked
        //MouseClicked
        evt.consume();
    }//GEN-LAST:event_panelComprasMouseClicked

    private void panelComprasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelComprasMouseExited
        //MouseExited
        evt.consume();
    }//GEN-LAST:event_panelComprasMouseExited

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        filtrar();
        posInicial +=6;
        JOptionPane.showMessageDialog(null, "Error al obtener los productos.");
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void imProducto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imProducto1MouseClicked
        abrirCarrito(0);
        evt.consume();
    }//GEN-LAST:event_imProducto1MouseClicked

    private void imProducto2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imProducto2MouseClicked
        abrirCarrito(1);
        evt.consume();
    }//GEN-LAST:event_imProducto2MouseClicked

    private void imProducto3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imProducto3MouseClicked
        abrirCarrito(2);
        evt.consume();
    }//GEN-LAST:event_imProducto3MouseClicked

    private void imProducto4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imProducto4MouseClicked
        abrirCarrito(3);
        evt.consume();
    }//GEN-LAST:event_imProducto4MouseClicked

    private void imProducto5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imProducto5MouseClicked
        abrirCarrito(4);
        evt.consume();
    }//GEN-LAST:event_imProducto5MouseClicked

    private void imProducto6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imProducto6MouseClicked
        abrirCarrito(5);
        evt.consume();
    }//GEN-LAST:event_imProducto6MouseClicked

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Catalogo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguiente;
    private org.edisoncor.gui.panel.PanelImage imProducto1;
    private org.edisoncor.gui.panel.PanelImage imProducto2;
    private org.edisoncor.gui.panel.PanelImage imProducto3;
    private org.edisoncor.gui.panel.PanelImage imProducto4;
    private org.edisoncor.gui.panel.PanelImage imProducto5;
    private org.edisoncor.gui.panel.PanelImage imProducto6;
    private javax.swing.JTabbedPane jtpMenu;
    private javax.swing.JLabel lblCamisas;
    public javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPantalones;
    private javax.swing.JLabel lblPoleras;
    private javax.swing.JLabel lblPolos;
    private javax.swing.JLabel lblProducto1;
    private javax.swing.JLabel lblProducto2;
    private javax.swing.JLabel lblProducto3;
    private javax.swing.JLabel lblProducto4;
    private javax.swing.JLabel lblProducto5;
    private javax.swing.JLabel lblProducto6;
    private javax.swing.JLabel lblZapatillas;
    private javax.swing.JLabel lblZapatos;
    private javax.swing.JPanel panelCategoria;
    private org.edisoncor.gui.panel.PanelImage panelImage18;
    private org.edisoncor.gui.panel.PanelImage panelImage19;
    private org.edisoncor.gui.panel.PanelImage panelImage4;
    private org.edisoncor.gui.panel.PanelImage panelImage5;
    private org.edisoncor.gui.panel.PanelImage pnlLupa;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
