/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frames.admin;

/**
 *
 * @author CRISTHIAN
 */
public class Inventario extends javax.swing.JPanel {
    private static final String FUENTE1 = "Segoe UI";
    public Inventario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel lblTitulo = new javax.swing.JLabel();
        javax.swing.JPanel line = new javax.swing.JPanel();
        javax.swing.JButton btnAdd = new javax.swing.JButton();
        javax.swing.JButton btnActualizar = new javax.swing.JButton();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(990, 721));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font(FUENTE1, 1, 24));
        lblTitulo.setForeground(new java.awt.Color(86, 105, 204));
        lblTitulo.setText("Actualizar inventario");
        add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 270, 40));

        line.setBackground(new java.awt.Color(86, 105, 204));
        add(line, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 500, 2));

        btnAdd.setFont(new java.awt.Font("FUENTE1", 0, 14));
        btnAdd.setText("Añadir nuevo producto");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 230, 50));

        btnActualizar.setFont(new java.awt.Font(FUENTE1, 0, 14));
        btnActualizar.setText("Actualizar producto");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 230, 50));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 710, 10, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        RegistrarProducto registro = new RegistrarProducto();
        registro.setVisible(true);
        evt.getActionCommand();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        ActualizarProductos update = new ActualizarProductos();
        update.setVisible(true);
        evt.getActionCommand();
    }//GEN-LAST:event_btnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
