/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frames.admin;

/**
 *
 * @author Lenovo
 */
public class Promociones extends javax.swing.JPanel {
    private static final String FUENTE1 = "Trebuchet MS";
    /**
     * Creates new form Promociones
     */
    public Promociones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        javax.swing.JLabel jLabel1;
        javax.swing.JPanel line = new javax.swing.JPanel();
        javax.swing.JLabel lblTitulo = new javax.swing.JLabel();
        javax.swing.JButton btnAdd2 = new javax.swing.JButton();
        javax.swing.JButton btnActualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(500, 721));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        line.setBackground(new java.awt.Color(86, 105, 204));
        add(line, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 500, 2));

        lblTitulo.setFont(new java.awt.Font(FUENTE1, 1, 24));
        lblTitulo.setForeground(new java.awt.Color(86, 105, 204));
        lblTitulo.setText("Promociones");
        add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 270, 40));

        btnAdd2.setFont(new java.awt.Font("FUENTE1", 0, 14));
        btnAdd2.setText("Ver Promociones");
        btnAdd2.addActionListener(this::btnAdd2ActionPerformed);
        add(btnAdd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 230, 50));

        btnActualizar.setFont(new java.awt.Font(FUENTE1, 0, 14));
        btnActualizar.setText("Crear Promociones");
        btnActualizar.addActionListener(this::btnActualizarActionPerformed);
        add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 230, 50));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd2ActionPerformed
        evt.getActionCommand();
    }//GEN-LAST:event_btnAdd2ActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        
        CrearPromociones cProm = new CrearPromociones();
        cProm.setVisible(true);
        evt.getActionCommand();
    }//GEN-LAST:event_btnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
